### ISSUE TITLE
calculate error about decimal part

### ISSUE THREAD

**Issue by zhiyuan2007** [skycoin/teller#154]
【calculate.go】calculate error about decimal part because btc value always is 0.123237, 1.2387654 and so on, primary reason was skycoin can't supprt decimal
testcase 
```
            {
                satoshis: 11345000, // 0.11345 BTC
                rate:     "100",
                result:   11000000, // 11 SKY
           },
```
```
        Error Trace:    calculate_test.go:90
    	Error:		Not equal: 0xa7d8c0 (expected)
    			        != 0xac6ca0 (actual)
    	Messages:	11000000 != 11300000
```

**Comment by zhiyuan2007** [comment]
tests on 
https://github.com/skycoin/teller/pull/156

https://github.com/skycoin/teller/pull/156/files/a2583c2d0dc5466a6783ce2807e807ae6b4bcec6..69a92513f435eb98e8fb012caad868c3955ed9a6

**Comment by gz-c** [comment]
It's ok,
the version of skycoin in the vendor lib has `daemon.MaxDropletPrecision = 1`, so it thinks it has 1 decimal place allowed.

I changed this to be a configurable value instead, #158
