### ISSUE TITLE
Additional endpoints for wallet OTC sales

### ISSUE THREAD

**Issue by montycrypto** [skycoin/teller#54]
The wallet could benefit from the following endpoints:

- Current rate at which Skycoins can be bought
- Wether Skycoins can be bought

**Comment by gz-c** [comment]
Added:

GET /api/config returns this:
```json
{
    "enabled": true,
    "confirmations_required": 1,
    "max_bound_btc_addrs": 5,
    "sky_btc_exchange_rate": "123.000000"
}```
