### ISSUE TITLE
Error in proxy public key generation using command "go run cmd/proxy/proxy.go"

### ISSUE THREAD

**Issue by ahsanaftab3** [skycoin/teller#60]
Clone the repository and try to run this command after generating btcaddresses.. the following errors are poping up 

cmd/proxy/proxy.go:43: cannot use *agent.Options literal (type *agent.Options) as type agent.Options in argument to agent.Listen
cmd/proxy/proxy.go:44: unknown field 'NoShutdownCleanup' in struct literal of type agent.Options
cmd/proxy/proxy.go:67: cannot use lseckey (type "github.com/skycoin/skycoin/src/cipher".SecKey) as type "github.com/skycoin/teller/vendor/github.com/skycoin/skycoin/src/cipher".SecKey in field value

**Comment by gz-c** [comment]
What is your go version

**Comment by ahsanaftab3** [comment]
1.8.3

**Comment by ahsanaftab3** [comment]
Found the Fix. code must not be outside GOPATH skycoin repo
