### ISSUE TITLE
Create fake btcd that reports deposits to teller

### ISSUE THREAD

**Issue by gz-c** [skycoin/teller#86]
Need a fake btcd that will report a deposit to teller. Should have an api for triggering a fake deposit.  This is so that teller can be tested without using real btc and waiting for block time.

**Comment by fox000002** [comment]
Should the api for triggering a fake deposit be integrated with btcrpcclient?

**Comment by gz-c** [comment]
No, as long as there is a cli command to trigger a fake deposit

**Comment by fox000002** [comment]
The scanner requests "getblock" and "getbestblock" to btcd. The fake btcd should response to these requests. Should the fake btcd read those info from config, or a local database that has stored some blocks from a true btcd?

**Comment by gz-c** [comment]
At first, no other data is needed to save.  Later I think the 2nd option: begin with a local database of real btcd data, can be done.
