### ISSUE TITLE
Support ETH deposits

### ISSUE THREAD

**Issue by gz-c** [skycoin/teller#92]

**Comment by zhiyuan2007** [comment]
use  "scan_meta" + "_" + coinType to store multi coins of scanner info ?
such as scan_meta_bitcoin, scan_meta_ethcoin ;
if that several interface need to be modified , 
from:
func (s *BTCStore) pushDepositTx(tx *bolt.Tx, dv Deposit) error {}
change to:
func (s *store) pushDepositValueTx(tx *bolt.Tx, dv DepositValue, cointype string) error {}

does this design ok?

**Comment by gz-c** [comment]
We can put them in the same "scan_meta" bucket but prefix the keys with coin name,
Or use nested buckets, but then the dbutil API might need changes

**Comment by zhiyuan2007** [comment]
nested bucket need change a lot code ,  use prefix also need change function parameters ,  better , (may be we can  create bucket for every coin)

**Comment by zhiyuan2007** [comment]
if support ethereum and bitcoin , the MaxBoundBtcAddresses of skycoin address is summary of all coins or only count of bitcoin ?
such as: if MaxBoundBtcAddresses =5 then  bind_list = [btc1, btc2, eth1,eth2, btc3] 
does this ok?

**Comment by gz-c** [comment]
Ok to use different buckets, it lets us create separate DBs if needed

For max bound addresses, you can count max for all addresses like that, I think that is easier

**Comment by zhiyuan2007** [comment]
did you has problem as follows: 
(also i am use bitcoind rather than btcd)
--------
type BtcRPCClient interface {
       GetBlockVerboseTx(*chainhash.Hash) (*btcjson.GetBlockVerboseResult, error)
       GetBlockVerbose(*chainhash.Hash) (*btcjson.GetBlockVerboseResult, error)
}
only GetBlockVerbose  worked on my computer, if GetBlockVerboseTx called , error was 
```
2017-11-28T21:45:51+08:00] ERROR btc.go:357 scanner.btc: btcClient.GetBlockVerboseTx failed blockHeight=496515 error="-1: getblock "blockhash" ( verbose )

If verbose is false, returns a string that is serialized, hex-encoded data for block 'hash'.
If verbose is true, returns an Object with information about block <hash>.

Arguments:
1. "blockhash"          (string, required) The block hash
2. verbose                (boolean, optional, default=true) true for a json object
```

**Comment by zhiyuan2007** [comment]
why not store last_scan_block info? scan from InitialScanHeight when teller restart everytime

**Comment by gz-c** [comment]
Because it adds too much complexity and you are forced to delete `last_scan_block` manually if there was an error and you need to reprocess.  It is easier to choose the start height.

**Comment by gz-c** [comment]
The start height is configurable

**Comment by zhiyuan2007** [comment]
ethereum and unit test is worked，i am test dummy module 
![image](https://user-images.githubusercontent.com/897759/33407873-47bc37fc-d5ae-11e7-92b5-953b4c31b82f.png)

**Comment by zhiyuan2007** [comment]
pull request https://github.com/skycoin/teller/pull/156
