### ISSUE TITLE
Scanning Bitcoin Wallet:  command line

### ISSUE THREAD

**Issue by skycoin-manager** [skycoin/teller#99]
Make folder "scanning wallet" and put cmd folder in there and one folder per command for this

---

Write a command utility that does the following

1> Writes a JSON file with bitcoin addresses (see skycoin/cmd/address_gen/address_gen.go )

- n is number of addresses to generate
- -seed="password" for the seed

2> Function that for scanning bitcoin block for deposits to a map of addresses

(command line function takes in list of addresses, get a particular block from BCTD and outputs the transactions that are deposits to addresses in the list fed in)

See: https://github.com/skycoin/teller/issues/98

- take in a bitcoin bitcoin block and a take in a map of addresses to watch
- output any transactions which deposit to addresses we are watching

include
- tx:ix (transaction hash, and index as string for output the transaction created)
- the hash of the block
- the hash of the parent block
- the block height

3> For  the JSON, foreach address in our json file, include

- uint64 "min_scanned_block", the lowest block height we have scanned for deposits to that address for
- uint64 "max_scanned_block", the highest block height we have scanned for deposits to that address for
- string, "max_block_hash", the hash of the lowest block we have scanned for
- a list of "Deposit Events" in JSON

- min_scanned_block starts at zero
- max_scanned block, starts at current block head or ?

Each deposit event must include
- "tx:id" string transaction id/hash and index (the output index for the transaction)
- hash of block for the transaction (and the index of the transaction in the block)
- parent of block
- block depth where transaction occurred

The array of deposit transactions must be sorted by the
- blockheight
- then by the transaction hash (if there are multiple deposit transaction with the same blockheight for a given index)

4> Create a command line argument that takes the JSON wallet and scans from block N to M, then updates the wallet JSON file by writing it back to disc.

- add every bitcoin address in the wallet file to the map of watched addresses
- scan every block from N to M, for deposits to addresses in the list of deposit addresses

IF block scanned is N and min_scan for an address is less than N
- verify that if scanning returns no deposit transactions in that block, that the JSON file does not have any deposits transactions recorded with that block height (zero transactions for address)
- verify that if scanning returns a transaction in that block, that the same tx:id does not appear else where in the array of recorded transactions with a different TX:ID pair
- verify that if scanning returns a transaction in that block, that the same tx:id does not appear else where in the array of recorded transactions (in the JSON file) with a different TX:ID pair
- verify that if scanning returns a transaction in that block, that the same tx:id does not appear else where in the array of recorded transactions (in the JSON file) with a different blockhash or blockheight
- verify that if scanning returns a deposit transaction for an address in that block, and N < min_scan, that the transaction is already recorded in the JSON file (with the exact same tx:index, block_height and block hash value)

IF block scanned is N and min_scan for an address is equal to N+1
- then if any new deposit transactions are detected, then add the deposits to the JSON file, in the list of deposit transactions for that address
- then increment min_scan by one
- then rescan the block again and make sure number of new/unknown transactions is zero
- if N is one greater than max_scan, then increment max_scan
- if N is not greater than min_scan, then do nothing

5> sorted ranges (for recording which blocks have been scanned)

"min_scan" and "max_scan" can be an array of structs.
- a struct storing sorted ranges
- merging ranges if they over lap
- getting the lowest range and highest range

Array like
[[0,3], [5,8]]
- means: we have scanned address from block 0 to 3, and from block 5 to 8
- then if we scan block 4 , then it becomes [[0,8]] because [[0,4], [5,8]] we have scanned from 0 to 4 and from 5 to 8 so can merge ranges and means have scanned from [0,8]
- the "4" is the gap. If number of ranges > 1, then we want function to get the first gap in the range
- we want function for telling us if an address has been scanned for a particular range
- we want function to update the ranges for a particular scan (we scanned 15, update ranges by incrementing any range that ends in 14).

**Simplified Version:**

We actually do not need an array of ranges. We actually only need 3 values (3 tuple)

The values are 

[x,y,z]
- x starts at zero (min_scan0 )
- y starts at the block the address was added to the watch list (min_scan1)
- z starts at Y is maximize block that we have scanned (max_scan)

If x is 0 and we scan block 1, we increment x to 1. If x is 3 and we scan 4, then we increment x. Once we have scanned from x to y then x will always equal y.

If  Y is 5 and we have scanned block 6, then we increment y by one ONLY if the value of X has reached Y.

if Z is 7 and we scan block 8, then we increment Z to 8.

Always check
- x <= y <= z
- If we scan blocks and find new transactions that were not recorded and the block height is between Y and Z, then error (they should have been recorded already)
- if we scan blocks and find new transactions and block height is between X and Y, then its ok/ no error (but we ignore them and do not add them unless, we are scanning block height X)

X - starts at lowest block and increments up
Y - starts at the block where the address was generated and increments up ONLY after X has reached Y
Z - starts at Y

Example:
- head block is 10

- we add address to watch list at block x
- starting value is [0,8,8]
- two new blocks are created (9 and 10)
- we scan 9
- value is now [0,8,9]
- we scan 0,1,2, up to 8
- value changes from [0,8,9] to [1,8,9] then [2,8,9] ... [8,8,9]
- we scan ten. value goes to [8,8,10]
- we scan 9 again, value goes to [9,9,10]  (the second only increments if its equal to the first)
- we scan 10, value goes to [10,10,10]

6>

Validation 1#
- make sure that if we scan a block we have already scanned, that we do not find a deposit for an address that is not already recorded (this is a bug, because we should have recorded it the first time it was scanned), Otherwise log error

Validate 2#
- make sure that if we have recorded a deposit for an address for block height N, that that the transaction appears when block N is scanned. (extract the deposits that have been recorded in the json file, for the block and check that when we scan the block that the transaction (tx:id, index, blockhash) is extracted from the block

7> 

A. for all addresses, get the lowest x value that needs to be scanned and scan 1 block forward

B. for all address, get the lowest z value that needs to be scanned and scan one block forward

We keep scanning A, then B alternating until z=y=z for all the blocks.

**Comment by gz-c** [comment]
This was moved to https://github.com/skycoin/services
